import { Card } from "@/lib/def";

export const SPELL_CARDS: Card[] = [
  {
    id: "61",
    name: "Vision with Eyes of Blue",
    type: "Spell",
    rarity: "Ultra Rare",
    description: `When you activate this card: You can reveal 1 "Blue-Eyes White Dragon" in your hand; Special Summon 1 monster from your hand.
    \nOnce per turn: You can target 1 face-up monster you control; return that face-up monster to the hand, then you can apply the following effect, based on the original name of the card returned to the hand.
    \n● "Blue-Eyes White Dragon": Special Summon 1 monster from your hand.
    \n● Other: Special Summon 1 "Blue-Eyes" monster from your hand.
    \nYou can only activate 1 "Vision with Eyes of Blue" per turn.`,
    attribute: "Continuous Spell",
    deckTypes: ["Blue-Eyes"],
    image: "/cards/spells/Vision with Eyes of Blue.webp",
  },
  {
    id: "62",
    name: "Ultimate Fusion",
    type: "Spell",
    rarity: "Super Rare",
    description: `During the Main Phase: Fusion Summon 1 Fusion Monster from your Extra Deck that mentions "Blue-Eyes White Dragon" or "Blue-Eyes Ultimate Dragon" as material, by shuffling the Fusion Materials listed on it from your hand, field, and/or GY into the Deck, then, you can destroy face-up cards your opponent controls, up to the number of "Blue-Eyes White Dragon" and "Blue-Eyes Ultimate Dragon" used from the field as material.
    \nYou can only activate 1 "Ultimate Fusion" per turn.`,
    attribute: "Quick-Play Spell",
    deckTypes: ["Blue-Eyes"],
    image: "/cards/spells/Ultimate Fusion.webp",
  },
  {
    id: "63",
    name: "Forbidden Droplet",
    type: "Spell",
    rarity: "Ultra Rare",
    description: `Send any number of other cards from your hand and/or field to the GY; choose that many Effect Monsters your opponent controls, and until the end of this turn, their ATK is halved, also their effects are negated.
    \nIn response to this card's activation, your opponent cannot activate cards, or the effects of cards, with the same original type (Monster/Spell/Trap) as the cards sent to the GY to activate this card.
    \nYou can only activate 1 "Forbidden Droplet" per turn.`,
    attribute: "Quick-Play Spell",
    deckTypes: ["Blue-Eyes", "Despia"],
    image: "/cards/spells/Forbidden Droplet.webp",
  },
  {
    id: "64",
    name: "The Melody of Awakening Dragon",
    type: "Spell",
    rarity: "Super Rare",
    description: `Discard 1 card; add up to 2 "Blue-Eyes" monsters with 3000 or more ATK from your Deck to your hand.`,
    attribute: "Normal Spell",
    deckTypes: ["Blue-Eyes"], 
    image: "/cards/spells/The Melody of Awakening Dragon.webp",
  },
  {
    id: "65",
    name: "Bingo Machine, Go!!!",
    type: "Spell",
    rarity: "Rare",
    description: `Reveal 3 cards from your Deck that each meets at least 1 of the criteria listed below, your opponent randomly picks 1 for you to add to your hand, and you shuffle the rest into your Deck.
    \nYou can only activate 1 "Bingo Machine, Go!!!" per turn.
    \n● "Blue-Eyes" monster
    \n● Spell/Trap that specifically lists the card "Blue-Eyes White Dragon" or "Blue-Eyes Ultimate Dragon", except "Bingo Machine, Go!!!"`,
    attribute: "Spell Card",
    deckTypes: ["Blue-Eyes"],
    image: "/cards/spells/Bingo Machine Go.webp",
  },
  {
    id: "66",
    name: "Mystical Space Typhoon",
    type: "Spell",
    rarity: "Ultra Rare",
    description: "Target 1 Spell/Trap on the field; destroy that target.",
    attribute: "Quick-Play Spell",
    image: "/cards/spells/Mystical Space Typhoon.webp",
    deckTypes: ["Blue-Eyes", "Despia"],
  },
  {
    id: "67",
    name: "Super Polymerization",
    type: "Spell",
    rarity: "Ultra Rare",
    description: `Discard 1 card; Fusion Summon 1 Fusion Monster from your Extra Deck, using monsters from either field as Fusion Material.
    \nNeither player can activate cards or effects in response to this card's activation.`,
    attribute: "Quick-Play Spell",
    deckTypes: ["Despia"],
    image: "/cards/spells/Super Polymerization.webp",
  },
  {
    id: "68",
    name: "Banishment of the Darklords",
    type: "Spell",
    rarity: "Ultra Rare",
    description: `Add 1 "Darklord" card from your Deck to your hand, except "Banishment of the Darklords".
    \nYou can only activate 1 "Banishment of the Darklords" per turn.`,
    attribute: "Normal Spell",
    deckTypes: ["Despia"],
    image: "/cards/spells/Banishment of the Darklords.webp",
  },
  {
    id: "69",
    name: "Branded in Red",
    type: "Spell",
    rarity: "Super Rare",
    description: `Target 1 "Despia" monster or "Fallen of Albaz" in your GY; add it to your hand, then you can apply the following effect.
    \n● Fusion Summon 1 Level 8 or higher Fusion Monster from your Extra Deck, by banishing Fusion Materials listed on it from your hand or field, but it cannot attack directly this turn.
    \nYou can only activate 1 "Branded in Red" per turn.`,
    attribute: "Normal Spell",
    deckTypes: ["Despia"],
    image: "/cards/spells/Branded in Red.webp",
  },
  {
    id: "70",
    name: "Branded Opening",
    type: "Spell",
    rarity: "Rare",
    description: `Discard 1 card, then take 1 "Despia" monster from your Deck, and either add it to your hand or Special Summon it in Defense Position, also for the rest of this turn after this card resolves, you cannot Special Summon monsters from the Extra Deck, except Fusion Monsters.
    \nIf a Fusion Monster(s) you control would be destroyed by card effect, you can banish this card from your GY instead.
    \nYou can only use each effect of "Branded Opening" once per turn.`,
    attribute: "Quick-Play Spell",
    deckTypes: ["Despia"],
    image: "/cards/spells/Branded Opening.webp",
  },
  {
    id: "71",
    name: "Despia, Theater of the Branded",
    type: "Spell",
    rarity: "Normal",
    description: `During your Main Phase: You can Fusion Summon 1 Level 8 or higher Fusion Monster from your Extra Deck, using monsters from your hand or field as Fusion Material.
    \nIf a face-up non-Fusion Fairy monster you control leaves the field by an opponent's card effect, or is destroyed by battle: You can target 1 Level 8 or higher Fusion Monster in your GY; Special Summon it.
    \nYou can only use each effect of "Despia, Theater of the Branded" once per turn.`,
    attribute: "Field Spell",
    deckTypes: ["Despia"],
    image: "/cards/spells/Despia Theater of the Branded.webp",
  },
  {
    id: "72",
    name: "Polymerization",
    type: "Spell",
    rarity: "Super Rare",
    description: `Fusion Summon 1 Fusion Monster from your Extra Deck, using monsters from your hand or field as Fusion Material.`,
    attribute: "Normal Spell",
    deckTypes: ["HERO"],
    image: "/cards/spells/Polymerization.webp",
  },
  {
    id: "73",
    name: "Rank-Up-Magic Numeron Force",
    type: "Spell",
    rarity: "Super Rare",
    description: `Target 1 face-up Xyz Monster you control; Special Summon from your Extra Deck, 1 "Number C" monster with the same Type as that monster you control, but 1 Rank higher, by using it as the Xyz Material. (This Special Summon is treated as an Xyz Summon. Xyz Materials attached to it also become Xyz Materials on the Summoned monster.)
    \nThen, if any face-up cards are on the field other than this card and the monster Summoned by it, negate the effects of those other card.`,
    attribute: "Normal Spell",
    deckTypes: ["Utopia"],
    image: "/cards/spells/Rank-Up-Magic Numeron Force.jpg",
  },
  {
    id: "74",
    name: "Sky Striker Mobilize - Engage!",
    type: "Spell",
    rarity: "Ultra Rare",
    description: `If you control no monsters in your Main Monster Zone: Add 1 "Sky Striker" card from your Deck to your hand, except "Sky Striker Mobilize - Engage!", then, if you have 3 or more Spells in your GY, you can draw 1 card.`,
    attribute: "Normal Spell",
    deckTypes: ["Sky Striker"],
    image: "/cards/spells/Sky Striker Mobilize - Engage!.jpg",
  },
  {
    id: "75",
    name: "Sky Striker Mecha - Eagle Booster",
    type: "Spell",
    rarity: "Rare",
    description: `If you control no monsters in your Main Monster Zone: Target 1 face-up monster on the field; that target is unaffected by card effects this turn, except its own, and if you have 3 or more Spells in your GY, it cannot be destroyed by battle this turn.`,
    attribute: "Quick-Play Spell",
    deckTypes: ["Sky Striker"],
    image: "/cards/spells/Sky Striker Mecha - Eagle Booster.jpg",
  },
  {
    id: "76", 
    name: "Sky Striker Mecha - Widow Anchor",
    type: "Spell",
    rarity: "Ultra Rare",
    description: `If you control no monsters in your Main Monster Zone: Target 1 face-up Effect Monster on the field; negate that face-up monster's effects until the end of this turn, then, if you have 3 or more Spells in your GY, you can take control of that monster until the End Phase.`,
    attribute: "Quick-Play Spell",
    deckTypes: ["Sky Striker"],
    image: "/cards/spells/Sky Striker Mecha - Widow Anchor.jpg",
  },
  {
    id: "77",
    name: "Sky Striker Mecha - Shark Cannon",
    type: "Spell",
    rarity: "Rare",
    description: `If you control no monsters in your Main Monster Zone: Target 1 monster in your opponent's GY; banish that monster, or, if you have 3 or more Spells in your GY, you can Special Summon that monster to your field instead, but it cannot attack.`,
    attribute: "Quick-Play Spell",
    deckTypes: ["Sky Striker"],
    image: "/cards/spells/Sky Striker Mecha - Shark Cannon.jpg",
  },
  {
    id: "78",
    name: "Sky Striker Maneuver - Scissors Cross",
    type: "Spell",
    rarity: "Normal",
    description: `If you control no monsters in your Main Monster Zone: Target 1 Level 4 "Sky Striker Ace" monster in your GY; add it to your hand, or if you have 3 or more Spells in your GY, you can Special Summon it instead.`,
    attribute: "Normal Spell",
    deckTypes: ["Sky Striker"],
    image: "/cards/spells/Sky Striker Maneuver - Scissors Cross.jpg",
  },
  {
    id: "79",
    name: "Sky Striker Maneuver - Afterburners!",
    type: "Spell",
    rarity: "Rare",
    description: `IIf you control no monsters in your Main Monster Zone: Target 1 face-up monster on the field; destroy it, then, if you have 3 or more Spells in your GY, you can destroy 1 Spell/Trap on the field.`,
    attribute: "Normal Spell",
    deckTypes: ["Sky Striker"],
    image: "/cards/spells/Sky Striker Maneuver - Afterburners!.jpg",
  },
  {
    id: "80", 
    name: "Sky Striker Maneuver - Jamming Waves!",
    type: "Spell",
    rarity: "Super Rare",
    description: `IIf you control no monsters in your Main Monster Zone: Target 1 Set Spell/Trap on the field; destroy it, then, if you have 3 or more Spells in your GY, you can destroy 1 monster on the field.`,
    attribute: "Normal Spell",
    deckTypes: ["Sky Striker"],
    image: "/cards/spells/Sky Striker Maneuver - Jamming Waves!.jpg", 
  },
  {
    id: "81",
    name: "Sky Striker Mobilize - Linkage!",
    type: "Spell",
    rarity: "Ultra Rare",
    description: `If you control no monsters in your Main Monster Zone: You cannot Special Summon monsters from the Extra Deck for the rest of this turn after this card resolves, except "Sky Striker Ace" monsters, also send 1 other card you control to the GY, and if you do, Special Summon 1 "Sky Striker Ace" monster from your Extra Deck to the Extra Monster Zone, and if you have at least 1 LIGHT and 1 DARK "Sky Striker Ace" monsters on your field and/or in your GY, the Summoned monster gains 1000 ATK.`,
    attribute: "Quick-Play Spell",
    deckTypes: ["Sky Striker"],
    image: "/cards/spells/Sky Striker Mobilize - Linkage!.jpg",
  },
  {
    id: "82",
    name: "Sky Striker Mobilize - Engage!",
    type: "Spell",
    rarity: "Ultra Rare",
    description: `If you control no monsters in your Main Monster Zone: Add 1 "Sky Striker" card from your Deck to your hand, except "Sky Striker Mobilize - Engage!", then, if you have 3 or more Spells in your GY, you can draw 1 card.`,
    attribute: "Normal Spell",
    deckTypes: ["Sky Striker"],
    image: "/cards/spells/Sky Striker Mobilize - Engage!.jpg",
  },
  {
    id: "83",
    name: "Sky Striker Airspace - Area Zero",
    type: "Spell",
    rarity: "Rare",
    description: `You can target 1 other card you control; excavate the top 3 cards of your Deck, and if you do, you can add 1 excavated "Sky Striker" card to your hand, also shuffle the rest into the Deck, then, if you excavated a "Sky Striker" card, send the targeted card to the GY.
If this card in the Field Zone is sent to the GY by a card effect: You can Special Summon 1 "Sky Striker Ace" monster from your Deck.
You can only use each effect of "Sky Striker Airspace - Area Zero" once per turn.`,
    attribute: "Field Spell",
    deckTypes: ["Sky Striker"],
    image: "/cards/spells/Sky Striker Airspace - Area Zero.jpg",
  },
  {
    id: "84",
    name: "Change of Heart",
    type: "Spell",
    rarity: "Ultra Rare",
    description: `Target 1 monster your opponent controls; take control of it until the End Phase.`,
    attribute: "Normal Spell",
    deckTypes: ["Shinato's Judgment"],
    image: "https://images.ygoprodeck.com/images/cards/4031928.jpg",
  }
]
